### ISSUE TITLE
Private keys must be instance of RSAPrivate(Crt)Key or have PKCS#8 encoding

### ISSUE THREAD

**Issue by waldandrade** [wmixvideo/nfe#148]
Pessoal .. fui atualizar a versão e deu isso abaixo:

Me ajudem por favor :(

javax.xml.crypto.dsig.XMLSignatureException: java.security.InvalidKeyException: Private keys must be instance of RSAPrivate(Crt)Key or have PKCS#8 encoding
	at org.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:412)
	at com.fincatto.nfe310.assinatura.AssinaturaDigital.assinarDocumento(AssinaturaDigital.java:106)
	at com.fincatto.nfe310.webservices.WSLoteEnvio.enviaLote(WSLoteEnvio.java:59)
	at com.fincatto.nfe310.webservices.WSFacade.enviaLote(WSFacade.java:53)
	at br.com.ceramic.assinador.util.Main.enviarXML(Main.java:263)
	at br.com.ceramic.assinador.util.Main.verificarEnviarXML(Main.java:223)
	at br.com.ceramic.assinador.util.Main.run(Main.java:402)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Private keys must be instance of RSAPrivate(Crt)Key or have PKCS#8 encoding
	at sun.security.rsa.RSAKeyFactory.translatePrivateKey(RSAKeyFactory.java:288)
	at sun.security.rsa.RSAKeyFactory.engineTranslateKey(RSAKeyFactory.java:191)
	at sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:111)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:106)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:99)
	at java.security.Signature$Delegate.init(Signature.java:1152)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1112)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1176)
	at java.security.Signature.initSign(Signature.java:527)
	at org.jcp.xml.dsig.internal.dom.DOMSignatureMethod.sign(DOMSignatureMethod.java:213)
	at org.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:409)
	... 7 more
java.security.InvalidKeyException: Private keys must be instance of RSAPrivate(Crt)Key or have PKCS#8 encoding
	at sun.security.rsa.RSAKeyFactory.translatePrivateKey(RSAKeyFactory.java:288)
	at sun.security.rsa.RSAKeyFactory.engineTranslateKey(RSAKeyFactory.java:191)
	at sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:111)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:106)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:99)
	at java.security.Signature$Delegate.init(Signature.java:1152)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1112)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1176)
	at java.security.Signature.initSign(Signature.java:527)
	at org.jcp.xml.dsig.internal.dom.DOMSignatureMethod.sign(DOMSignatureMethod.java:213)
	at org.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:409)
	at com.fincatto.nfe310.assinatura.AssinaturaDigital.assinarDocumento(AssinaturaDigital.java:106)
	at com.fincatto.nfe310.webservices.WSLoteEnvio.enviaLote(WSLoteEnvio.java:59)
	at com.fincatto.nfe310.webservices.WSFacade.enviaLote(WSFacade.java:53)
	at br.com.ceramic.assinador.util.Main.enviarXML(Main.java:263)
	at br.com.ceramic.assinador.util.Main.verificarEnviarXML(Main.java:223)
	at br.com.ceramic.assinador.util.Main.run(Main.java:402)
	at java.lang.Thread.run(Thread.java:745)
java.security.InvalidKeyException: Private keys must be instance of RSAPrivate(Crt)Key or have PKCS#8 encoding
	at sun.security.rsa.RSAKeyFactory.translatePrivateKey(RSAKeyFactory.java:288)
	at sun.security.rsa.RSAKeyFactory.engineTranslateKey(RSAKeyFactory.java:191)
	at sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:111)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:106)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:99)
	at java.security.Signature$Delegate.init(Signature.java:1152)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1112)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1176)
	at java.security.Signature.initSign(Signature.java:527)
	at org.jcp.xml.dsig.internal.dom.DOMSignatureMethod.sign(DOMSignatureMethod.java:213)
	at org.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:409)
	at com.fincatto.nfe310.assinatura.AssinaturaDigital.assinarDocumento(AssinaturaDigital.java:106)
	at com.fincatto.nfe310.webservices.WSLoteEnvio.enviaLote(WSLoteEnvio.java:59)
	at com.fincatto.nfe310.webservices.WSFacade.enviaLote(WSFacade.java:53)
	at br.com.ceramic.assinador.util.Main.enviarXML(Main.java:263)
	at br.com.ceramic.assinador.util.Main.verificarEnviarXML(Main.java:223)
	at br.com.ceramic.assinador.util.Main.run(Main.java:402)
	at java.lang.Thread.run(Thread.java:745)

**Comment by waldandrade** [comment]
Resolvi!!!! ..... Glória a Deus!! Que tava infartando já aqui.

**Comment by jefperito** [comment]
👍

**Comment by fmpinheiro** [comment]
Seria importante incluir qual é a solução, pois assim se alguém mais enfrentar este problema já tem a solução (e não enfarta, rs).

**Comment by waldandrade** [comment]
Certo...

Esse erro acontece quando de alguma maneira definimos 2 vezes o PrivateKey.

Basta procurar uma segunda definição do KeyStore e do Provider.

De certo ... devemos sempre puxar a instância do KeyStore, e verificar,
através do "getProvider", se ele está "null", ou já está definido.

**Comment by fincatto** [comment]
Ou, mas simples e eficaz, fazer um cache do KeyStore na classe que extende
e NFeConfig.
Veja o exemplo: https://github.com/wmixvideo/nfe/tree/assinatura


2016-05-19 23:17 GMT-03:00 waldandrade <notifications@github.com>:

**Comment by waldandrade** [comment]
Exatamente ... no meu caso eu tava criando esse cache, mas tinha um trecho
duplicado, por falha minha mesmo.

Em 20 de maio de 2016 08:16, Diego Fincatto <notifications@github.com>
escreveu:

> Ou, mas simples e eficaz, fazer um cache do KeyStore na classe que extende
> e NFeConfig.
> Veja o exemplo: https://github.com/wmixvideo/nfe/tree/assinatura
>
>
>
> 2016-05-19 23:17 GMT-03:00 waldandrade <notifications@github.com>:
>
> > Certo...
> >
> > Esse erro acontece quando de alguma maneira definimos 2 vezes o
> PrivateKey.
> >
> > Basta procurar uma segunda definição do KeyStore e do Provider.
> >
> > De certo ... devemos sempre puxar a instância do KeyStore, e verificar,
> > através do "getProvider", se ele está "null", ou já está definido.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wmixvideo/nfe/issues/148#issuecomment-220501278>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/148#issuecomment-220580092>
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*
