### ISSUE TITLE
Falha no processo de envio

### ISSUE THREAD

**Issue by henriquebartoski** [wmixvideo/nfe#151]
Boa tarde.

Já estou utilizando o Nfe a alguns meses, utilizando 4 certificados diferentes e todos funcionais até então, porém me deparei com uma situação inesperada após a atualização de um dos certificados que utilizo.

Ao tentar enviar uma nfe ao Sefaz utilizando o certificado atualizado obtenho um StringIndexOutOfBoundsException, sendo que os outros certificados funcionam normalmente e este mesmo certificado funciona perfeitamente no nosso sistema emissor antigo.

Os processos de consulta estão funcionando normalmente. Cancelamento e inutilização ainda não pude testar.

Segue a pinha de exceção:

`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at java.security.PKCS12Attribute.<init>(PKCS12Attribute.java:88)
	at sun.security.pkcs12.PKCS12KeyStore.getAttributes(PKCS12KeyStore.java:1391)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1287)
	at java.security.KeyStore.getEntry(KeyStore.java:1521)
	at com.fincatto.nfe310.assinatura.AssinaturaDigital.assinarDocumento(AssinaturaDigital.java:79)
	at com.fincatto.nfe310.webservices.WSLoteEnvio.enviaLote(WSLoteEnvio.java:59)
	at com.fincatto.nfe310.webservices.WSFacade.enviaLote(WSFacade.java:53)
	at br.inf.ideiasistemas.controller.nfe.ControllNfe.envia(ControllNfe.java:294)
	at br.inf.ideiasistemas.controller.nfe.ControllNfe.main(ControllNfe.java:64)`

Caso alguém possa dar alguma contribuição fico muito grato!

**Comment by fincatto** [comment]
Se você olhar a linha do erro, vai ver que é onde o sistema tenta pegar o Alias do certificado.
Possivelmente está sem (facil confirmar com debug), então sugiro reexportar ou verificar se o certificado realmente está ok.

**Comment by henriquebartoski** [comment]
De fato era o Alias que estava vazio. Alterei o certificado através do MMC do Windows incluindo o Alias e o problema foi resolvido.

Caso alguém precise é só seguir os passos: https://technet.microsoft.com/pt-br/library/cc725909(v=ws.11).aspx

Além disso também constatei que o suporte da Certisign não sabe nada além de pedir para instalar e desinstalar o certificado (30 minutos escutando isso) rsrs.

Obrigado!

**Comment by RenatoTrindade** [comment]
Vocês utilizaram o Certificado no moto PFX ou o instalado na maquina? se tiver como me mostra codigo de como você utilizaram o certificado, pois o meu está com alias e não ta funcionando..
