### ISSUE TITLE
Tratamento de erro no envio de NFC-e

### ISSUE THREAD

**Issue by andre-campos** [wmixvideo/nfe#220]
Estou tendo um problema com o envio de uma NFC-e de serviços no Amazonas. Não sei se o erro é causado pela SEFAZ ou há, de fato, algum problema com o arquivo que estou enviando. O arquivo é aceito normalmente pelo sistema de homologação, mas ocorre uma exceção ao tentar mandá-lo para o sistema de produção:
```
org.simpleframework.xml.core.ElementException: Element 'nRec' does not have a match in class com.fincatto.nfe310.classes.lote.envio.NFLoteEnvioRetorno at line 1
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at org.simpleframework.xml.core.Persister.read(Persister.java:499)
	at org.simpleframework.xml.core.Persister.read(Persister.java:408)
	at com.fincatto.nfe310.webservices.WSLoteEnvio.comunicaLote(WSLoteEnvio.java:109)
```

A resposta é um XML válido, mas certamente um formato inesperado. Para ver o conteúdo da resposta, habilitei o debug das comunicações http (`-Djavax.net.debug=all`). A resposta que estou recebendo é esta:
```
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
	<soapenv:Body>
		<nfeAutorizacaoLoteResult xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao">
			<retConsReciNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
				<tpAmb>1</tpAmb>
				<verAplic>AM3.10</verAplic>
				<nRec>130002323144651</nRec>
				<cStat>765</cStat>
				<xMotivo>Rejeicao: Lote so podera conter NF-e ou NFC-e</xMotivo>
				<cUF>13</cUF>
				<dhRecbto>2016-08-26T00:03:54-04:00</dhRecbto>
			</retConsReciNFe>
		</nfeAutorizacaoLoteResult>
	</soapenv:Body>
</soapenv:Envelope>
```

O motivo da rejeição me parece um mistério e terei que resolver isto com a SEFAZ local, mas acredito que só faça sentido lançar uma exceção nestes casos se ela contiver a mensagem do elemento `<xMotivo/>`.

**Comment by andre-campos** [comment]
A tag `<nfeAutorizacaoLoteResult/>` pode ter basicamente qualquer coisa, conforme mostram os wsdls do Amazonas e do Ceará, por exemplo  (https://nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao?wsdl; https://nfe.sefaz.ce.gov.br/nfe2/services/NfeAutorizacao?wsdl). Já o de Minas Gerais especifica que a resposta do lote seja do tipo `retEnviNFe`, que é o esperado por esta biblioteca.

O formato da resposta que estou recebendo é, no mínimo, tosco. Isto me faz acreditar que há um problema na SEFAZ do amazonas, que está gerando uma resposta com a tag errada (`retConsReciNFe`). Como é difícil "chutar" o que vai estar dentro de `<nfeAutorizacaoLoteResult />`, talvez seja interessante dar um `try...catch` na interpretação da resposta e logar o conteúdo dela em caso de erro.
