### ISSUE TITLE
ERRO - ("Sender sendViaPost INFORMAÇÕES: Unable to sendViaPost to url[https://nfe-homologacao.svrs.rs.gov.br /ws/NfeStatusServico/NfeStatusServico2.asmx])

### ISSUE THREAD

**Issue by caiocteodoro** [wmixvideo/nfe#240]
Alguém que utiliza a biblioteca para transmissão das notas já passou por esse erro "Unable to sendViaPost to url"?
Tenho um aplicativo desktop que faz a assinatura e transmissão dos XMLs para o certificado A3.
Este erro ocorre somente com o certificado A3 acessando a sefaz RS e SVRS. Já tentei praticamente de tudo e nada.
Se alguém que passou por isso puder ajudar seria de grande avalia, já estou brigando com esse erro a uns 15 dias.

Segue o erro completo:

```
set 29, 2016 4:46:19 PM org.apache.axis2.transport.http.HTTPSender sendViaPost
INFORMAÃıES: Unable to sendViaPost to url[https://nfe-homologacao.svrs.rs.gov.br
/ws/NfeStatusServico/NfeStatusServico2.asmx]
javax.net.ssl.SSLHandshakeException: Error signing certificate verify
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:
78)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106
)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.
java:1116)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$Http
ConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMetho
dBase.java:1973)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodB
ase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.j
ava:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Htt
pMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMe
thodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.jav
a:397)
        at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(Abst
ractHTTPSender.java:621)
        at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.jav
a:193)
        at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessa
geWithCommons(CommonsHTTPTransportSender.java:396)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(Com
monsHTTPTransportSender.java:223)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisO
peration.java:406)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(Out
InAxisOperation.java:229)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:
165)
        at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServi
co2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
        at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus
(WSStatusConsulta.java:66)
        at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSSta
tusConsulta.java:34)
        at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java
:99)
        at org.agely.nfe.servico.consultastatus.NfeConsultaStatus.retornoNfeCons
ultaStatus(NfeConsultaStatus.java:40)
        at org.agely.nfe.servico.classes.AcionaServico.nfeStatusServico(AcionaSe
rvico.java:65)
        at org.agely.nfe.servico.classes.AcionaServico.verificaTipoServico(Acion
aServico.java:33)
        at org.agely.nfe.swing.TelaPrincipal$1$1.run(TelaPrincipal.java:133)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
Caused by: java.security.InvalidKeyException: Unsupported key type: SunPKCS11-Sm
artCard RSA private key, 2048 bits (id 1, token object, sensitive, unextractable
)
        at sun.security.mscapi.RSACipher.engineGetKeySize(RSACipher.java:425)
        at javax.crypto.Cipher.passCryptoPermCheck(Cipher.java:1067)
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1025)
        at javax.crypto.Cipher.init(Cipher.java:1245)
        at java.security.Signature$CipherAdapter.engineInitSign(Unknown Source)
        at java.security.Signature$Delegate.init(Unknown Source)
        at java.security.Signature$Delegate.chooseProvider(Unknown Source)
        at java.security.Signature$Delegate.engineInitSign(Unknown Source)
        at java.security.Signature.initSign(Unknown Source)
        at sun.security.ssl.RSASignature.engineInitSign(Unknown Source)
        at java.security.Signature$Delegate.engineInitSign(Unknown Source)
        at java.security.Signature.initSign(Unknown Source)
        at sun.security.ssl.HandshakeMessage$CertificateVerify.<init>(Unknown So
urce)
        ... 38 more

org.apache.axis2.AxisFault: Error signing certificate verify
        at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
        at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.jav
a:197)
        at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessa
geWithCommons(CommonsHTTPTransportSender.java:396)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(Com
monsHTTPTransportSender.java:223)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisO
peration.java:406)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(Out
InAxisOperation.java:229)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:
165)
        at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServi
co2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
        at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus
(WSStatusConsulta.java:66)
        at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSSta
tusConsulta.java:34)
        at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java
:99)
        at org.agely.nfe.servico.consultastatus.NfeConsultaStatus.retornoNfeCons
ultaStatus(NfeConsultaStatus.java:40)
        at org.agely.nfe.servico.classes.AcionaServico.nfeStatusServico(AcionaSe
rvico.java:65)
        at org.agely.nfe.servico.classes.AcionaServico.verificaTipoServico(Acion
aServico.java:33)
        at org.agely.nfe.swing.TelaPrincipal$1$1.run(TelaPrincipal.java:133)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: Error signing certificate verify

        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:
78)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106
)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.
java:1116)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$Http
ConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMetho
dBase.java:1973)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodB
ase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.j
ava:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Htt
pMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMe
thodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.jav
a:397)
        at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(Abst
ractHTTPSender.java:621)
        at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.jav
a:193)
        ... 17 more
Caused by: java.security.InvalidKeyException: Unsupported key type: SunPKCS11-Sm
artCard RSA private key, 2048 bits (id 1, token object, sensitive, unextractable
)
        at sun.security.mscapi.RSACipher.engineGetKeySize(RSACipher.java:425)
        at javax.crypto.Cipher.passCryptoPermCheck(Cipher.java:1067)
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1025)
        at javax.crypto.Cipher.init(Cipher.java:1245)
        at java.security.Signature$CipherAdapter.engineInitSign(Unknown Source)
        at java.security.Signature$Delegate.init(Unknown Source)
        at java.security.Signature$Delegate.chooseProvider(Unknown Source)
        at java.security.Signature$Delegate.engineInitSign(Unknown Source)
        at java.security.Signature.initSign(Unknown Source)
        at sun.security.ssl.RSASignature.engineInitSign(Unknown Source)
        at java.security.Signature$Delegate.engineInitSign(Unknown Source)
        at java.security.Signature.initSign(Unknown Source)
        at sun.security.ssl.HandshakeMessage$CertificateVerify.<init>(Unknown So
urce)
        ... 38 more
```

**Comment by caiocteodoro** [comment]
Tenho um usuário no DF que é credenciado pela SEFAZ SVRS e esse utiliza o certificado A1.
Este consegue fazer os procedimentos normalmente, o erro acontece mesmo somente com o A3!
