### ISSUE TITLE
Certificado A1 - Alias

### ISSUE THREAD

**Issue by RenatoTrindade** [wmixvideo/nfe#246]
O meu certificado A1 não possui Alias, ai quando vou assinar apresenta o seguinte erro:

`java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at java.security.PKCS12Attribute.<init>(PKCS12Attribute.java:88)
	at sun.security.pkcs12.PKCS12KeyStore.getAttributes(PKCS12KeyStore.java:1391)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1287)
	at java.security.KeyStore.getEntry(KeyStore.java:1521)
	at com.fincatto.nfe310.assinatura.AssinaturaDigital.assinarDocumento(AssinaturaDigital.java:79)
	at com.fincatto.nfe310.NFePrincipal.main(NFePrincipal.java:67)`

Alguém já teve esse problema?

**Comment by henriquebartoski** [comment]
https://github.com/wmixvideo/nfe/issues/151
