### ISSUE TITLE
javax.net.ssl.SSLHandshakeException ao autorizar pela SVRS

### ISSUE THREAD

**Issue by fabianofsantos** [wmixvideo/nfe#296]
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

Estou tentando enviar por contigência mas sempre recebo esta exception. Pela sefaz de origem funciona normal. alguém já passou por isso?

**Comment by fincatto** [comment]
Esse erro indica que você não tem o certificado correto instalado.
