### ISSUE TITLE
Problemas com o certificado, erro : Connection has been shutdown, PKIX path building failed, unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by jhonattan471** [wmixvideo/nfe#330]
Hey, 

Fiz o download do projeto para testar suas funcionalidades, fiz os seguintes passos : 

+---------------------------------------------------------+
    Alterações
       criei um novo pacote onde coloquei 2 classes : 
+---------------------------------------------------------+

em "NFeConfigTeste"
...
InputStream certificadoStream = new FileInputStream("meucertificado.pfx")
InputStream cadeia = new FileInputStream("certificado.jks")
...

em  "Main"
...
NFeConfigTeste config = new NFeConfigTeste();		
NFStatusServicoConsultaRetorno retorno = 
                                   new WSFacade(config).consultaStatus(NFUnidadeFederativa.PR, NFModelo.NFE);
...

+------------------------+
  Problema = cacerts?
+------------------------+

Fiz o download dos cacerts, eles foram movidos pra meu c:/tmp/
Ao tentar rodar o projeto, recebi o erro que esta no console output abaixo, 
tentei substituir o cacerts do meu jdk/lib/security pelo de homologacao que baixei mas o problema persistiu

alguém tem alguma ideia do que pode ser ?

+----------------+
  console output  
+----------------+
log4j:WARN No appenders could be found for logger (org.apache.axiom.locator.DefaultOMMetaFactoryLocator).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:621)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:193)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:67)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:36)
	at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java:105)
	at meu.main.main(main.java:28)
Caused by: com.ctc.wstx.exc.WstxIOException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:261)
	at org.apache.axiom.util.stax.wrapper.XMLStreamWriterWrapper.flush(XMLStreamWriterWrapper.java:50)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.close(MTOMXMLStreamWriter.java:224)
	at org.apache.axiom.om.impl.common.AxiomContainerSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomContainerSupport$org_apache_axiom_om_impl_common_AxiomContainer$serializeAndConsume(AxiomContainerSupport.aj:320)
	at org.apache.axiom.om.impl.llom.OMElementImpl.serializeAndConsume(OMElementImpl.java:1)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
	... 21 more
Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.SSLSocketImpl.checkEOF(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.checkWrite(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.FilterOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.ChunkedOutputStream.flush(ChunkedOutputStream.java:191)
	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:103)
	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:225)
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:259)
	... 26 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.FilterOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.ChunkedOutputStream.flush(ChunkedOutputStream.java:191)
	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:103)
	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:225)
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:259)
	at org.apache.axiom.util.stax.wrapper.XMLStreamWriterWrapper.flush(XMLStreamWriterWrapper.java:50)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.flush(MTOMXMLStreamWriter.java:232)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj:49)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:1)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethodDispatch1$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj:32)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:1)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub$NfeDadosMsg.serialize(NfeStatusServico2Stub.java:1354)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub$NfeDadosMsg.serialize(NfeStatusServico2Stub.java:1329)
	at org.apache.axis2.databinding.ADBDataSource.serialize(ADBDataSource.java:90)
	at org.apache.axiom.om.impl.common.serializer.push.stax.StAXSerializer.serializePushOMDataSource(StAXSerializer.java:53)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serialize(Serializer.java:369)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:646)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serializeChildren(Serializer.java:279)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:485)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serializeChildren(Serializer.java:279)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:485)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:201)
	at org.apache.axiom.om.impl.common.AxiomContainerSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomContainerSupport$org_apache_axiom_om_impl_common_AxiomContainer$serializeAndConsume(AxiomContainerSupport.aj:313)
	... 23 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 57 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 63 more

**Comment by RamonKenedy** [comment]
Eu estou com um problema parecido:
javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca 
Pelo que pesquisei o problema é com os arquivos cacerts mesmo.
"Para a cadeia de certificados da SEFAZ necessária para o acesso, utilize a cadeia da unidade certificadora que emitiu o seu certificado. " Essa informação esta no README deste projeto.
O meu problema só ocorre com o certificado da Valid, com o de outras certificadoras funciona normalmente.
Nesse link tem uma solução que talvez funcione pra vc:
http://www.javac.com.br/jc/posts/list/1779-resolvidonfseerro-sslhandshakeexception-received-fatal-alert-unknownca-eou-handshakefailure.page

**Comment by fincatto** [comment]
Bom dia pessoal.
Vocês chegaram a usar a classes que faz o download dos CACerts que vem com o projeto?
Estou usando eles aqui, sem problemas até agora.
Att

**Comment by RamonKenedy** [comment]
Bom dia!
Sim, eu usei a classe NFGeraCadeiaCertificados como no exemplo do Readme.
No meu caso, só tenho o erro javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca quando é ambiente de homologação em Goiás. Quando uso o ambiente de produção em Goias ou o ambiente de homologação de outro estado não ocorre o problema.

**Comment by fincatto** [comment]
Você chegou a conferir se a URL do serviço está correta?

**Comment by RamonKenedy** [comment]
Sim, pelo menos o método getNfeStatusServico() da classe NFAutorizador31 esta retornando a mesma URL disponível no site da SEFAZ em ambiente de homologação. Porque nem o serviço de consulta status do serviço esta funcionando, ocorre o mesmo erro.
Pelo que pesquisei creio que seja alguma coisa relacionada a cadeia de certificados da Valid, mais já atualizei ela e testei em vários sistema operacionais e computadores diferentes e ate o momento não encontrei uma solução.

**Comment by fincatto** [comment]
Alguma novidade com este certificado?

**Comment by andersonajx** [comment]
Alguma novidade com esse problema? Também estou passando pelo mesmo problema.

Estou usando Ubuntu 16, Java 8 e o certificado é da Valid.

**Comment by lucasmbrito** [comment]
O certificados de vocês foram emitidos de novembro até o dia de hoje ?

**Comment by RamonKenedy** [comment]
Sim, o meu foi emitido em 22/02/2017 pela Valid.

**Comment by lucasmbrito** [comment]
Os certificados que foram emitidos nesse período estão com a Hierarquia v5, e até segunda-feira a Sefaz não tinha atualizado o servidor para receber essa nova hierarquia.
Mandei e-mail e liguei diversas vezes, para eles atualizarem. 

Gera o Cacerts e instala o certificado novamente que deve funcionar, agora que a sefaz atualizou o servidor.

**Comment by RamonKenedy** [comment]
Blz, valeu Lucas!
Vou fazer isso e aviso aqui se funcionou!

**Comment by RamonKenedy** [comment]
Gerei os cacerts e reinstalei o certificado, porem o erro:
Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
continua acontecendo!

**Comment by lucasmbrito** [comment]
Os certificados que vc tem e estão funcionando são da  hierarquia v5 ?

**Comment by RamonKenedy** [comment]
Tanto esse certificado que deu erro(Valid) quanto o que esta funcionando(Soluti) estão como Versão V3.
Porem o certificado que esta funcionando foi emitido dia 15/07/2016.
Um detalhe que percebi agora, que não sei se tem a ver, é que o certificado que esta ocorrendo o erro não possui o Nome Amigável.

**Comment by lucasmbrito** [comment]
Da uma olhada nesse link 
http://www.javac.com.br/jc/posts/list/2782-certificado-digital-a1-sem-nome-amigavel.page

**Comment by RamonKenedy** [comment]
Coloquei o nome amigável mais não resolveu!
Valeu pela dica!

**Comment by Samuel-Oliveira** [comment]
Olá! Depois de muito Testar e verificar Descobri um Jeito de como Resolver: 
Na Classe de NFSocketFactory.java, no metodo createSSLContext  eu alterei o SSLProtocol de 'TLSv1' para 'TLS'.
E funcionou perfeitamente.
Porem, vocês usam variável para definir esse SSLProtocol, e utilizam em dois métodos diferentes, createSocket e createSSLContext. Assim ao colocar 'TLS' o createSocket da Pau.

Então para funcionar, a  createSocket deve ser 'TLSv1' e a createSSLContext 'TLS'.

Abraços!

**Comment by lucasmbrito** [comment]
Algué conseguiu atualizar o Cacerts ?

Estou tendo o mesmo erro para fazer a manifestação do destinatário.

**Comment by rootrey** [comment]
Estou com o mesmo problema no ambiente de homologação Sefaz GO, já tentei a solução do Samuel e não resolveu, alguém teria alguma outra ideia ?

**Comment by danieldhp** [comment]
Passei por este problema hoje com a sefaz MS, para corrigir precisei gerar o cacerts novamente.

Utilizei esta classe [link javac](http://www.javac.com.br/jc/posts/list/34-nfe-geracao-do-arquivo-cacerts-para-todos-os-estados-unico-arquivo.page) mas alterei os endereços pelos que estão no site da nfe.fazenda [(link)](http://www.nfe.fazenda.gov.br/portal/WebServices.aspx) pois este exemplo é antigo, e muitos dos endereços mudaram

**Comment by lucasmbrito** [comment]
Fiz um mesmo um tempo atrás, utilizei outra classe para gerar os cacerts e deu certo.

**Comment by fauker** [comment]
Tive esse problema em produção anteontem com um cliente do GO. Pra resolver eu só gerei os cacerts novamente com as próprias classes do projeto.

**Comment by tisof001** [comment]
Olá. Eu estava tendo este mesmo problema, atualizei os cacerts mas outro erro começou a aparecer em alguns estados (funciona somente no RS e SP). O que devo fazer?

`INFORMAÇÕES: Retrying request
ago 02, 2017 8:45:47 AM org.apache.axis2.transport.http.HTTPSender sendViaPost
INFORMAÇÕES: Unable to sendViaPost to url[https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2]
org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:621)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:193)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:67)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:36)
	at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java:105)
	at br.com.lohr.monitor.scpl.funcoes.FuncaoPF.verificarStatusServicoSEFAZ(FuncaoPF.java:202)
	at br.com.lohr.monitor.scpl.controle.teste.main(teste.java:21)
Caused by: com.ctc.wstx.exc.WstxIOException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:261)
	at org.apache.axiom.util.stax.wrapper.XMLStreamWriterWrapper.flush(XMLStreamWriterWrapper.java:50)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.close(MTOMXMLStreamWriter.java:224)
	at org.apache.axiom.om.impl.common.AxiomContainerSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomContainerSupport$org_apache_axiom_om_impl_common_AxiomContainer$serializeAndConsume(AxiomContainerSupport.aj:320)
	at org.apache.axiom.om.impl.llom.OMElementImpl.serializeAndConsume(OMElementImpl.java:1)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
	... 22 more
Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.ChunkedOutputStream.flush(ChunkedOutputStream.java:191)
	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:103)
	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:225)
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:259)
	... 27 more
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1870)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.ChunkedOutputStream.flush(ChunkedOutputStream.java:191)
	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:103)
	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:225)
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:259)
	at org.apache.axiom.util.stax.wrapper.XMLStreamWriterWrapper.flush(XMLStreamWriterWrapper.java:50)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.flush(MTOMXMLStreamWriter.java:232)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj:49)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:1)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethodDispatch1$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj)
	at org.apache.axiom.om.impl.common.AxiomSerializableSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomSerializableSupport$org_apache_axiom_om_impl_common_AxiomSerializable$serialize(AxiomSerializableSupport.aj:32)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:1)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub$NfeDadosMsg.serialize(NfeStatusServico2Stub.java:1354)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub$NfeDadosMsg.serialize(NfeStatusServico2Stub.java:1329)
	at org.apache.axis2.databinding.ADBDataSource.serialize(ADBDataSource.java:90)
	at org.apache.axiom.om.impl.common.serializer.push.stax.StAXSerializer.serializePushOMDataSource(StAXSerializer.java:53)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serialize(Serializer.java:369)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:646)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serializeChildren(Serializer.java:279)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:485)
	at org.apache.axiom.om.impl.common.serializer.push.Serializer.serializeChildren(Serializer.java:279)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:485)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:201)
	at org.apache.axiom.om.impl.common.AxiomContainerSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomContainerSupport$org_apache_axiom_om_impl_common_AxiomContainer$serializeAndConsume(AxiomContainerSupport.aj:313)
	... 24 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	... 49 more`

**Comment by caiocteodoro** [comment]
Bom dia.

A sua aplicação é WEB ou DESKTOP?

2017-08-02 8:47 GMT-03:00 tisof001 <notifications@github.com>:

**Comment by tisof001** [comment]
Bom dia,
É desktop e uso certificado A1.

**Comment by caiocteodoro** [comment]
Já passei pelo mesmo problema com uma aplicação desktop, mas com a
utilização do certificado A3.
O .jar quando executado não conseguia fazer a comunicação com a SEFAZ.
Sempre retornava o erro 'Unable to sendViaPost to url', a maneira que
encontrei de fazer foi executar o projeto com comando direto assim
funcionou normal.

start javaw.exe -cp .;..\lib\* caminho.para.Main >NUL


Criei um arquivo .bat com a seguinte instrução:


@echo off
cd bin >NUL
start javaw.exe -cp .;..\lib\* caminho.para.Main >NUL
EXIT


E dentro da pasta que contém este arquivo coloque também as classes
compiladas do projeto e as libs.


2017-08-02 9:16 GMT-03:00 tisof001 <notifications@github.com>:

**Comment by tisof001** [comment]
O que esse bat deveria faz exatamente? Tentei mas não consegui fazer esse BAT funcionar.

**Comment by caiocteodoro** [comment]
Ele executa sua aplicação, sem ser pelo .jar.
O sua aplicação desktop é java?

Em 2 de agosto de 2017 15:20, tisof001 <notifications@github.com> escreveu:

**Comment by tisof001** [comment]
Na verdade é um serviço que roda em um servidor linux, mas é feito em Java sim.

**Comment by elyelrubens** [comment]
Tive este problema recentemente, começou a acontecer do nada, sem nem mesmo atualizar o java, creio que é alguma alteração nos web services da NF-e.

Resolvi gerando o cacerts antes de cada requisição aos web services.

Não consegui entender o motivo pelo qual o cacert gerado funciona na primeira requisição e na segunda em diante da este erro.

**Comment by tisof001** [comment]
Tentei gerar ele antes de cada requisição mas continua o mesmo erro.

Meu NFeConfig esta assim:
`
@Override
    public NFUnidadeFederativa getCUF() {
        return NFUnidadeFederativa.RS;
    }

    @Override
    public NFAmbiente getAmbiente() {
        if (se serviço rodando no servidor de producao) {
            return NFAmbiente.PRODUCAO;
        } else {
            return NFAmbiente.HOMOLOGACAO;
        }
    }

    @Override
    public String getCertificadoSenha() {
        return "123456";
    }

    @Override
    public String getCadeiaCertificadosSenha() {
        return "123456";
    }

    @Override
    public KeyStore getCertificadoKeyStore() throws KeyStoreException {
        if (this.keyStoreCertificado == null) {
            this.keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = new FileInputStream(System.getenv("CAMINHO_CERTIFICADO_NFE_EMPRESA"))) {
                this.keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Não foi possivel montar o KeyStore com a Cadeia de Certificados", e);
            }
        }
        return this.keyStoreCertificado;
    }

    @Override
    public KeyStore getCadeiaCertificadosKeyStore() throws KeyStoreException {
        if (this.keyStoreCadeia == null) {
            this.keyStoreCadeia = KeyStore.getInstance("JKS");
            try (InputStream a = new ByteArrayInputStream(NFGeraCadeiaCertificados.geraCadeiaCertificados(getAmbiente(), getCadeiaCertificadosSenha()))) {
                this.keyStoreCadeia.load(a, this.getCadeiaCertificadosSenha().toCharArray());
            } catch (Exception e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Não foi possivel montar o KeyStore com a Cadeia de Certificados", e);
            }
        }
        return this.keyStoreCadeia;
    }
`

E estou apenas testando o status:
`
     NFeConfigEMPRESA CONFIG_NFE_EMPRESA = new NFeConfigEMPRESA();
     NFStatusServicoConsultaRetorno retorno = new WSFacade(EMPRESA ).consultaStatus(NFUnidadeFederativa.SP, NFModelo.NFE);
     NFStatusServicoConsultaRetorno retorno = new WSFacade(EMPRESA ).consultaStatus(NFUnidadeFederativa.RS, NFModelo.NFE);
     NFStatusServicoConsultaRetorno retorno = new WSFacade(EMPRESA ).consultaStatus(NFUnidadeFederativa.MG, NFModelo.NFE);
`

Mas somente RS e SP funcionam.
