### ISSUE TITLE
[Homologacao] Certificado que está na branch master é valido para testes ?

### ISSUE THREAD

**Issue by EliveltonRepolho** [wmixvideo/nfe#346]
Boa tarde pessoal,

estou iniciando a implementa da NFe para um cliente aqui no estado de SP.

Para testes iniciais, até porque o cliente pediu o certificado agora, estou tentando utilizar o "homologacao.pfx" que esta na branch master.

Mas quando tento consultar o status dos WebServices de acordo com o exemplo daqui mesmo, me retorna o erro:

`
org.apache.axis2.AxisFault: Transport error: 403 Error: Forbidden
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:310)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:194)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:66)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:34)
	at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java:105)
	at com.home.sistema.nfe.NfeTest.teste2(NfeTest.java:52)
`

Gerei tudo certinho as cadeias de certificado também... Estou desconfiado que é por causa do certificado mesmo, confere ?

**Comment by lucasmbrito** [comment]
Cara ja tive diversas vezes esse problema, agora a sefaz atualizou os certificados para hierarquia v5, eu gerei um Cacerts que funcionou, só que tenho novos certificados e estou tendo o mesmo erro novamente.

**Comment by fincatto** [comment]
Também tive problemas com certificados novos, porém na GNRE, não na NFE.
Nossos certificados era gerados pelos Correios, e tivemos que trocar de
certificadora.

2017-07-20 9:38 GMT-03:00 lucasmbrito <notifications@github.com>:

**Comment by lucasmbrito** [comment]
Qual certificadora vc mudou @fincatto ?

**Comment by fincatto** [comment]
Dos Correios para Fenacon.

**Comment by lucasmbrito** [comment]
@EliveltonRepolho tenta fazer esse procedimento, eu fiz e deu certo.

http://www.guj.com.br/t/nfe-erro-403-7-forbidden-ao-acessar-webservices-asmx-resolvido/296277/2

**Comment by EliveltonRepolho** [comment]
Pessoal, desculpa pela demora, mas nesses últimos dias não consegui pegar nesse projeto dinovo.

Como nesse meu caso era uma NFe bem simples, acabei colocando direto para o cliente testar em produção mesmo, fiz uma comparação antes do xml gerado pela lib e os valores bateram, então blz rs.

No caso o problema estava no ambiente de homologação eu acredito mesmo, pq em prod rolou com o certificado do cliente.

**Comment by fauker** [comment]
@EliveltonRepolho legal! Acho que você pode fechar esta issue então.

**Comment by odione** [comment]
Tambem tive o mesmo problema! pelo navegador funciona, mas pelo axis para o sefaz virtual do RS, nao funciona, erro 403 forbiden! mas o WS de SP funciona! certificado emitido pelos correios, cadeia serpro V5! ainda nao consegui resolver
