### ISSUE TITLE
NFC-e 

### ISSUE THREAD

**Issue by dafivero** [wmixvideo/nfe#350]
Boa tarde. 

Estou usando o projeto de vocês para emissão de NF-e aqui na empresa e está tudo funcionando normalmente. Porém me foi solicitado verificar se a emissão de NFC-e pode ser feita também. Pesquisando algumas coisas aqui, verifiquei que tem esta possibilidade, mas fui testar a consulta do serviço para SP e está dando o erro abaixo. Se mudo o modelo para NFE o retorno é 107 - Serviço em operação. 

Alguém pode me ajudar, já tentei de tudo aqui. Sei que é algum problema com certificado, mas para NFe não dá este retorno.

Desde já agradeço.

Estou usando o seguinte codigo:

NFStatusServicoConsultaRetorno retorno = new WSFacade(config).consultaStatus(NFUnidadeFederativa.SP, NFModelo.NFCE);
			System.out.println(retorno.getStatus());
			System.out.println(retorno.getMotivo());

Retorno:

[INFO] 28 jul 03:39:11.666 PM main [org.apache.commons.httpclient.HttpMethodDirector]
I/O exception (org.apache.axis2.AxisFault) caught when processing request: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[INFO] 28 jul 03:39:11.667 PM main [org.apache.commons.httpclient.HttpMethodDirector]
Retrying request

[INFO] 28 jul 03:39:11.729 PM main [org.apache.commons.httpclient.HttpMethodDirector]
I/O exception (org.apache.axis2.AxisFault) caught when processing request: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[INFO] 28 jul 03:39:11.729 PM main [org.apache.commons.httpclient.HttpMethodDirector]
Retrying request

[INFO] 28 jul 03:39:11.793 PM main [org.apache.commons.httpclient.HttpMethodDirector]
I/O exception (org.apache.axis2.AxisFault) caught when processing request: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[INFO] 28 jul 03:39:11.794 PM main [org.apache.commons.httpclient.HttpMethodDirector]
Retrying request

[INFO] 28 jul 03:39:11.853 PM main [org.apache.axis2.transport.http.HTTPSender]
Unable to sendViaPost to url[https://homologacao.nfce.fazenda.sp.gov.br/ws/nfestatusservico2.asmx]

org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:621)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:193)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:67)
	at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:36)
	at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java:105)
	at com.nfefederal.MainTeste.main(MainTeste.java:30)

**Comment by fincatto** [comment]
Parece ser problema com a cadeia, e não com o certificado em si.
Você pode gerar uma nova cadeia, pra testar? Garanta que o certificado do servidor de destino esteja nessa cadeia.
Att

**Comment by dafivero** [comment]
Eu fiz a geração da cadeia antes de consumir o serviço, mas mesmo assim continua com problemas.
Utilizei o keytool para listar e está presente o certificado.

SubjectAlternativeName [
  DNSName: homologacao.nfce.fazenda.sp.gov.br
  Other-Name: Unrecognized ObjectIdentifier: 2.16.76.1.3.8
  Other-Name: Unrecognized ObjectIdentifier: 2.16.76.1.3.3
  Other-Name: Unrecognized ObjectIdentifier: 2.16.76.1.3.2
  Other-Name: Unrecognized ObjectIdentifier: 2.16.76.1.3.4
]

Porém, se mudo o modelo para NFE não dá erro nenhum. Utilizando mesma cadeira de certificado.

Vou pesquisar aqui mais sobre o assunto e se achar a solução posto aqui.

Obrigado.

**Comment by elyelrubens** [comment]
Isto pode ser pelo tipo de protocolo de comunicação utilizado com o web service, já resolvi este problema a um tempo atrás apenas alterando o protocolo. 

A partir da versão 4.0 da NFe será permitido unicamente o protocolo TLS 1.2 ou versão superior. Ou seja, não será mais permitida à comunicação via protocolo SSL

Tive este problema com um certificado digital A3 gerado neste mês, resolvi atualizando a versão do certificado para TLSv1.2

**Comment by UnoSolucoes** [comment]
Desculpa a demora na resposta, fiquei meio doente este período e também precisei priorizar alguns outros projetos.
Na verdade estava testando com SP a consulta do serviço e por algum motivo dá este erro, algumas outras unidades federativas que testei ( BA, RS, RN ) está funcionando a consulta do serviço.
Talvez SP tenha o problema por que há a necessidade de se utilizar o SAT.
Tentei mudar o certificado como sugerido mas também está dando problema. 
O fato é que se faço a consulta do serviço de NF-e, funciona normalmente, somente o NFC-e é que dá problema. A chamada que estou fazendo é a seguinte:

NFeConfigTeste config = new NFeConfigTeste();
	        config.setAmbiente(NFAmbiente.HOMOLOGACAO);
	        config.getCertificadoKeyStore();
	        config.getCadeiaCertificadosKeyStore();
	        
			NFStatusServicoConsultaRetorno retorno = new WSFacade(config).consultaStatus(NFUnidadeFederativa.SP, NFModelo.NFCE);
			System.out.println(retorno.getStatus());
			System.out.println(retorno.getMotivo());

Obrigado pela ajuda. 

Abraços.

**Comment by fincatto** [comment]
Aqui em SC tb temos problemas com a NFCe. Acho que ainda não está 100%, em todas as UFs.
