### ISSUE TITLE
Problema ao comunicar com a receita na versão 4.00, erro certificado desconhecido

### ISSUE THREAD

**Issue by marlosmorbis** [wmixvideo/nfe#412]
Bom dia Pessoal,

Estamos enfrentando um problema com alguns clientes para a transmissão da NF para a receita, o problema aconteceu quando migramos nossos códigos para a versão 4.00. A maioria de nossos clientes a nota está emitindo normal já na 4.00, para apenas 2 clientes quando vai já consultar a disponibilidade da receita para fazer o envio da nota ele retorna o erro:

```
org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:621)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:193)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.documentofiscal.nfe400.webservices.statusservico.consulta.NfeStatusServico4Stub.nfeStatusServicoNF(NfeStatusServico4Stub.java:125)
	at com.fincatto.documentofiscal.nfe400.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:58)
	at com.fincatto.documentofiscal.nfe400.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:34)
	at com.fincatto.documentofiscal.nfe400.webservices.WSFacade.consultaStatus(WSFacade.java:108)
	at br.com.controlenamao.util.notaFiscal.NotaFiscalLoteEnvio.verificarDisponibilidadeSefaz(NotaFiscalLoteEnvio.java:356)
```

O que percebemos para esses clientes, foi uma coisa, o certificado deles são do tipo A1 (Todos os outros clientes que funcionam também são), a extensão original era .p12 e não .pfx e os dois são emitidos pela mesma Autoridade Certificadora SERPRORFBv5.
Mas um ponto curioso é que com esses mesmos certificados na versão 3.10 emiti a nota normalmente.

Peço a ajuda dos senhores para uma possível solução para esse problema. Alguém tem alguma ideia do que pode estar acontecendo ?

Desde já agradeço pela ajuda.

**Comment by fincatto** [comment]
Bom dia.
Você deve tentar, primeiramente, atualizar a cadeia de certificados. 
Se não funcionar, é preciso saber se o servidor da Sefaz reconhece a sua certificadora (como mudaram o endpoint, pode ser que não conheçam mais).
Nós tivemos um problema parecido com este aqui na empresa, mas relacionado com a GNRE. Eles pararam de aceitar nosso certificado, emitido pelos Correios. Tivemos que emitir um novo certificado, atraves do CDL, para poder usar o serviço.
Att

**Comment by eldevanjr** [comment]
Olá, tive um problema parecido num cliente com certificado A3 da OBERTHUR, na versao anterior ele funcionava corretamente, mas depois de atualizar acontecia o mesmo erro, depois de estudar um pouco descobri que o erro era que na versão do NFE antiga era usado o TLSv1 e passava , depois que foi atualizado para TLSv2 ele deixada de autorizar, sendo que precisei setar o TLS pra v1 pra poder passar, e corrigiu o erro, não sei se pode ser isso, mas fica a dica.Veja um exemplo do código que precisei colocar pra funcionar:
```java
if(StringUtils.containsIgnoreCase(text, "OcsCryptoki.dll")) {
    this.setSslProtocols(new String[]{"TLSv1"});
}

**Comment by marlosmorbis** [comment]
Obrigado @fincatto pelo retorno.
Regerei a cadeia de certificados NfeCacerts, e sem sucesso! Agora entrei em contato com a receita para tentar uma solução, ficaram de me dar um retorno da área mais técnica em até 2 dias úteis, mas não sei não se vai retornar com a solução.. rsrs,

Novamente agradeço o retorno,

**Comment by marlosmorbis** [comment]
Obrigado @eldevanjr pelo retorno.
Tentei a solução que passou, fiz um override do método  `getSSLProtocolos` na minha Config para retornar a versão TLSv1, não deu sucesso também, voltou o mesmo erro.

Agradeço pela atenção.

**Comment by marlosmorbis** [comment]
Bom dia Senhores,

Conseguimos resolver o problema dos certificados dos Clientes. Depois de contatos com a Certificadora e a empresa que nos vendeu o certificado, que não ajudaram em nada. Fomos para o contato com a Receita, no nosso caso a Receita do Paraná, expliquei o problema pra eles e a solução foi um tanto simples, faltavam adicionar para aceitar a Certificadora no ficheiro de certificados do lado servidor deles, fizeram isso e a conexão funcionou normalmente.

Novamente, obrigado pela ajuda. 
Atenciosamente,

**Comment by fincatto** [comment]
Muito obrigado por compartilhar a solução.
Me espantou que a receita lhes ajudou. Tenho alguns chamados feitos na Sefaz de SC e do RS, e nunca tive sequer resposta.
