### ISSUE TITLE
Erro ao efetuar Manifestação de Destinatário - Recepção de Eventos 4.00

### ISSUE THREAD

**Issue by marquesjr** [wmixvideo/nfe#420]
Olá pessoal.

Estou com problemas no envio de eventos do tipo Manifestação de Destinatário na versão 4.00.
Incluí os protocolos TLSv1.1 e TLSv1 ao método _getSSLProtocolos_ em DFConfig.java, pois estava me retornando uma exceção. A saber:

`org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Server chose TLSv1.1, but that protocol version is not enabled or not supported by the client.
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:621)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:193)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:396)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:223)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.documentofiscal.nfe400.webservices.gerado.NFeRecepcaoEvento4Stub.nfeRecepcaoEvento(NFeRecepcaoEvento4Stub.java:136)`

Feito isso, consegui enviar eventos, menos eventos de manifestação. Quando tento enviar esse tipo de evento, tenho a seguinte exceção:

`org.apache.axis2.AxisFault: Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento' was not recognized.
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:375)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.documentofiscal.nfe400.webservices.gerado.NFeRecepcaoEvento4Stub.nfeRecepcaoEvento(NFeRecepcaoEvento4Stub.java:136)`

Alguém poderia me ajudar? Desde já, obrigado.

**Comment by henriquebartoski** [comment]
Alguma solução foi encontrada?

**Comment by fincatto** [comment]
Ainda não utilizamos manifestação aqui na empresa, então não consigo testar aqui. 
Alguém mais está com problema?

**Comment by marquesjr** [comment]
Alguém encontrou solução?

**Comment by fincatto** [comment]
Você chegou a verificar se a url do serviço (
http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento)
está correta?
Como não estamos usando a manifestação aqui, fica mais difícil de gerar um
teste ou comparar com o seu.
Att

**Comment by marquesjr** [comment]
Olá, @fincatto .
Já verifiquei a URL, de acordo com a sefaz (https://www.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx?wsdl) está correta.
O que estou estranhando é o fato de apenas a manifestação estar com esse problema, uma vez que os outros eventos utilizam a mesma URL no mesmo método (método nfeRecepcaoEvento na classe NFeRecepcaoEvento4Stub).

**Comment by ACMedis** [comment]
Na classe NFAutorizador400.java, eu mudei os endereços, para versão 4.0, no Ambiente Nacional "AN".

**Comment by marquesjr** [comment]
@ACMedis, seria possível postar as alterações aqui nos comentários?

**Comment by ACMedis** [comment]
`AN {
        @Override
        public String getRecepcaoEvento(final DFAmbiente ambiente) {
            return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://hom.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx" : "https://www.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx";
        }

        @Override
        public String getNfeAutorizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfeRetAutorizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfeConsultaProtocolo(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfeStatusServico(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getConsultaCadastro(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfeInutilizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceAutorizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceRetAutorizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceConsultaCadastro(final DFAmbiente ambiente) {
            return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? null : null;
        }

        @Override
        public String getNfceConsultaProtocolo(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceStatusServico(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceRecepcaoEvento(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getNfceInutilizacao(final DFAmbiente ambiente) {
            return null;
        }

        @Override
        public String getRecepcaoEventoAN(final DFAmbiente ambiente) {
            return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://hom.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx" : "https://www.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx";
        }

        @Override
        public String getNFeDistribuicaoDFe(final DFAmbiente ambiente) {
            return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://hom.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx" : "https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx";
        }

        @Override
        public DFUnidadeFederativa[] getUFs() {
            return new DFUnidadeFederativa[] {};
        }
    },`

Na classe NFeAutorizador400.java eu alterei o endereço deste método: getNFeDistribuicaoDFe, conforme o código acima.

**Comment by mgraciano** [comment]
Alguém está trabalhando em uma correção deste problema? Confirmo que a alteração proposta pelo @ACMedis realmente resolve o problema. Caso contrário vou providenciar um pull request com a correção assim que possível.

**Comment by marquesjr** [comment]
Confirmo que as seguintes alterações solucionam o problema:
1 - Inclusão do protocolo TLSv1.1 ao método _getSSLProtocolos_ em _DFConfig.java_;
2 - Atualização das URLs em NFeAutorizador400.java, conforme sugerido por @ACMedis.

Obrigado a todos os envolvidos!  :)
