### ISSUE TITLE
SOAP message MUST NOT contain a Document Type Declaration(DTD)

### ISSUE THREAD

**Issue by danielgweb** [wmixvideo/nfe#478]
Ao tentar baixar uma nota informando o cnpj e a chave, o seguinte erro ocorre:

`org.apache.axis2.AxisFault: SOAP message MUST NOT contain a Document Type Declaration(DTD)
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:123)
	at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:67)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:354)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.documentofiscal.nfe310.webservices.downloadnf.NfeDownloadNFStub.nfeDownloadNF(NfeDownloadNFStub.java:127)
	at com.fincatto.documentofiscal.nfe310.webservices.WSNotaDownload.efetuaDownloadNF(WSNotaDownload.java:61)
	at com.fincatto.documentofiscal.nfe310.webservices.WSNotaDownload.downloadNota(WSNotaDownload.java:38)
	at com.fincatto.documentofiscal.nfe310.webservices.WSFacade.downloadNota(WSFacade.java:240)`

**Comment by danielbohnrs** [comment]
Um cliente meu teve este mesmo erro no envio da NF-e (ambiente SVRS):

`org.apache.axis2.AxisFault: SOAP message MUST NOT contain a Document Type Declaration(DTD)
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:123)
	at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:67)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:354)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at com.fincatto.documentofiscal.nfe400.webservices.gerado.NFeAutorizacao4Stub.nfeAutorizacaoLote(NFeAutorizacao4Stub.java:104)
	at com.fincatto.documentofiscal.nfe400.webservices.WSLoteEnvio.comunicaLote(WSLoteEnvio.java:113)
	at com.fincatto.documentofiscal.nfe400.webservices.WSLoteEnvio.enviaLote(WSLoteEnvio.java:48)
	at com.fincatto.documentofiscal.nfe400.webservices.WSFacade.enviaLote(WSFacade.java:72)
	at br.com.sistacografo.dao.NotaFiscalEletronicaProdutoDao.enviarNota(NotaFiscalEletronicaProdutoDao.java:662)
	at br.com.sistacografo.view.controllers.NotaFiscalEletronicaProdutoController.enviar(NotaFiscalEletronicaProdutoController.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

Logo após o erro foi outro:

`Caused by: java.net.UnknownHostException: nfe.svrs.rs.gov.br
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)`


Pelo que pesquisei, o primeiro erro acontece quando o servidor retorna algo diferente do esperado (XML), como erro HTTP 502, 503, 504....

De qualquer forma, parece ser um erro momentâneo e no máximo o que pode ser feito é mostrar uma mensagem 'amigável' ao usuário.

![image](https://user-images.githubusercontent.com/9351538/47806452-96937580-dd18-11e8-8547-8d900a1b51f3.png)
