### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#480]
Bom dia!
Estou recebendo esse erro quando tento executar meu projeto: 

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:275)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:977)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)`

Estou tentando fazer uns testes de uma implementação para gerar o DANFE. Já limpei, mas não funciona. Procurando aqui nos foruns da vida, vi que tem algo haver com o Manifest, mas não consegui resolver. Alguém já passou por isso?
Grato.

**Comment by gilmario-kpslow** [comment]
se você descrever em que parte do código ocorre a exceção poder ser mais
fácil de identificar. O que você etá tentando fazer? Compilar o projeto?
teste?

Em ter, 17 de jul de 2018 às 10:34, José Allison <notifications@github.com>
escreveu:

**Comment by AllisonErd** [comment]
@gilmario-kpslow obrigado por responder. 
O que estou tentando fazer é rodar a aplicação normalmente.
A parte do código que adicionei, e deu erro foi essa:
```

public void imprimirDanfe(NotaFiscal nf) {
        try {
            DFParser parser = new DFParser();
            NFNotaProcessada notaProcessada = parser.notaProcessadaParaObjeto(carregarXmlNFNota(nf.getNfeChaveAcesso()).toString());
            NFDanfeReport danfe = new NFDanfeReport(notaProcessada);
            JasperPrint print;
            print = danfe.createJasperPrintNFe(Util.getBytesLogo("/home/allison/Imagens/hp.jpg"));
            JasperPrintManager.printReport(print, true);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (ParserConfigurationException ex) {
            System.out.println(ex.getMessage());
        } catch (SAXException ex) {
            System.out.println(ex.getMessage());
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
    }

```
Além dos arquivos JRXML e Jasper. Depois, fui rodar pra ver se estava funcionando e apareceu isso.

**Comment by edigomes** [comment]
Esse esse não parece ter a ver com a lib e sim na configuração do seu
projeto dá uma olhada aqui:
https://stackoverflow.com/questions/999489/invalid-signature-file-when-attempting-to-run-a-jar

Em Ter, 17 de jul de 2018 14:11, José Allison <notifications@github.com>
escreveu:

**Comment by edigomes** [comment]
Esse erro*

Em Ter, 17 de jul de 2018 14:24, Edi Gomes <edi.gomes00@gmail.com> escreveu:

**Comment by AllisonErd** [comment]
@edigomes obrigado por responder.
Então, nas minhas pesquisas, achei esse link. Adicionei alguns plugins do maven, outras configurações no pom, e mesmo assim da o erro. Já tentei recarregar o pom, e tbm não funciona.

**Comment by AllisonErd** [comment]
Resolvi o problema. 
Adicionei isso aqui `<excludes>META-INF/*.SF,META-INF/*.DSA,META-INF/*.RSA</excludes>` dentro do configuration do `maven-dependency-plugin` e funcionou.
Obrigado a todos que comentaram!
