### ISSUE TITLE
Erro ao fazer parser da nota

### ISSUE THREAD

**Issue by petersonschmitt** [wmixvideo/nfe#529]
Olá, pessoal estou tendo o seguinte problema ao tentar fazer o parser da nota para o objeto NFNota, fiz validação do xml e o xml é válido.

codigo:
```
....
List<NFDistribuicaoDocumentoZip> docZipList = retorno.getLote().getDocZip();
			for (NFDistribuicaoDocumentoZip docZip : docZipList) {
				String resNFe = WSDistribuicaoNFe.decodeGZipToXml(docZip.getValue());
				final NFNota nota = new DFParser().notaParaObjeto(resNFe);
			}
```

erro:
```
java.lang.IllegalArgumentException: Nao foi possivel parsear o xml: Attribute 'versao' does not have a match in class integrator.documents.nfe400.classes.nota.NFNota at line 1
	at integrator.documents.nfe400.parsers.DFParser.notaParaObjeto(DFParser.java:40)
	at nfe.Teste.main(Teste.java:46)
```

**Comment by danielbohnrs** [comment]
Quando ainda não foi executada a Manifestação do Destinatário sobre a nota, é retornada apenas a versão resumida dela, por isso da erro ao fazer `new DFParser().notaParaObjeto(resNFe)` (compara a estrutura do xml contida em `resNFe` com o xml de uma nota que já foi feito a manifestação de ciência da operação).

**Comment by petersonschmitt** [comment]
@danielbohnrs , muito obrigado pela resposta, exatamente isso, estava vendo uma issue
[resNFe_v1.01.xsd](https://github.com/wmixvideo/nfe/issues/468) que fala exatamente isso.
Porem estou com outra duvida, uma nota que esta como `<nfeProc versao="4.00"` .....
porem a mesma está invalida, existe uma forma de ver qual é o erro desta nota? ao tentar converter a nota deu erro, executei um validador de um site de terceiros é o mesmo me informou que a nota estava invalida `Rejeição[362]: Rejeição: Venda de combustível sem informação do Transportador.`.

**Comment by danielbohnrs** [comment]
@petersonschmitt dentro da rotina `new com.fincatto.documentofiscal.nfe400.webservices.WSFacade(this.configuracaoNfe).enviaLote(lote);` é executada a validação do lote, conforme os schemas (.xsd).
