### ISSUE TITLE
Nova cadeia de certificados Sefaz/MS

### ISSUE THREAD

**Issue by rafaelstelles** [wmixvideo/nfe#957]
Olá, recebi a mensagem abaixo do Sefaz/MS há alguns atrás e entendi que não seria necessário fazer nada do lado da lib, porém hoje as emissões começaram a dar erro e retornar a seguinte mensagem.

Vocês sabem me dizer se é preciso mudar algo aqui do lado da lib ?

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
```

<img width="597" alt="image" src="https://github.com/wmixvideo/nfe/assets/6481101/cf327cbc-e6ae-4593-9e1e-2e21151634d9">

**Comment by danielbohnrs** [comment]
Se tu abrir a url do webservice do navegador, verá que o certificado SSL do domínio não está válido, por isso que não está conseguindo criar um canal seguro para comunicação

![image](https://github.com/wmixvideo/nfe/assets/9351538/ec6ea4e4-5d05-4034-8ecd-81cf6a88318e)

**Comment by rafaelstelles** [comment]
Sim, porém eu acessei a de MG e aconteceu mesma coisa.

Link: https://nfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4

Será que é só isso mesmo ?

**Comment by danielbohnrs** [comment]
Chegou a tentar regerar os cacerts e enviar uma nota?

Att.
Daniel José Bohn
Engenheiro de Computação
________________________________
De: Rafael Sanches Telles ***@***.***>
Enviado: quarta-feira, 17 de abril de 2024 19:27
Para: wmixvideo/nfe ***@***.***>
Cc: Daniel José Bohn ***@***.***>; Comment ***@***.***>
Assunto: Re: [wmixvideo/nfe] Nova cadeia de certificados Sefaz/MS (Issue #957)


Sim, porém eu acessei a de MG e aconteceu mesma coisa.

Link: https://nfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4

Será que é só isso mesmo ?

**Comment by rafaelstelles** [comment]
Eu gerei o cacerts e deu certo no ambiente de homologação, porém produção continua com erro, porém agora é outro

```
Caused by: com.ctc.wstx.exc.WstxIOException: Connection or outbound has closed
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:262)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.flush(MTOMXMLStreamWriter.java:231)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.close(MTOMXMLStreamWriter.java:223)
	at org.apache.axiom.om.impl.common.AxiomContainerSupport.ajc$interMethod$org_apache_axiom_om_impl_common_AxiomContainerSupport$org_apache_axiom_om_impl_intf_AxiomContainer$serializeAndConsume(AxiomContainerSupport.aj:324)
	at org.apache.axiom.om.impl.llom.OMElementImpl.serializeAndConsume(OMElementImpl.java:1)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
```

**Comment by rafaelstelles** [comment]
Para funcionar em produção, eu tive que importar os novos certicados na VM, e dessa forma funcionou sem erros.
